# Generated by Django 5.2.3 on 2025-07-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=2)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(default='Not Specified', max_length=10)),
                ('phone_number', models.CharField(max_length=10)),
                ('percentage', models.FloatField()),
                ('student_bio', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('registration', models.DateTimeField()),
            ],
        ),
    ]
